Build: Resolve all violating non final res references for main
This is an AGP version '8.0' breaking change that changes the build
option default values, see build failure below:

PS: The alternative would be to disable the default, that is, having the
'android.nonFinalResIds' disabled, and not resolve all violating such
res references. However, because this didn't require a significant
amount extra work, nor much testing is needed, it is best not to ignore
this default so as to force this behavior going forward.

------------------------------------------------------------------------

> Task :WooCommerce:compileWasabiDebugKotlin FAILED
e: file:///Users/.../WooCommerce/src/main/kotlin/com/woocommerce/
android/model/ProductCategory.kt:21:63
Const 'val' initializer should be a constant value
e: file:///Users/.../WooCommerce/src/main/kotlin/com/woocommerce/
android/ui/jetpack/JetpackInstallProgressDialog.kt:35:43
Const 'val' initializer should be a constant value
e: file:///Users/.../WooCommerce/src/main/kotlin/com/woocommerce/
android/ui/jetpack/JetpackInstallProgressDialog.kt:36:39
Const 'val' initializer should be a constant value
e: file:///Users/.../WooCommerce/src/main/kotlin/com/woocommerce/
android/ui/payments/feedback/ipp/GetIPPFeedbackBannerData.kt:138:49
Const 'val' initializer should be a constant value
e: file:///Users/.../WooCommerce/src/main/kotlin/com/woocommerce/
android/ui/payments/feedback/ipp/GetIPPFeedbackBannerData.kt:139:51
Const 'val' initializer should be a constant value
e: file:///Users/.../WooCommerce/src/main/kotlin/com/woocommerce/
android/ui/payments/feedback/ipp/GetIPPFeedbackBannerData.kt:140:48
Const 'val' initializer should be a constant value
e: file:///Users/.../WooCommerce/src/main/kotlin/com/woocommerce/
android/ui/payments/feedback/ipp/GetIPPFeedbackBannerData.kt:142:51
Const 'val' initializer should be a constant value
e: file:///Users/.../WooCommerce/src/main/kotlin/com/woocommerce/
android/ui/payments/feedback/ipp/GetIPPFeedbackBannerData.kt:143:53
Const 'val' initializer should be a constant value
e: file:///Users/.../WooCommerce/src/main/kotlin/com/woocommerce/
android/ui/payments/feedback/ipp/GetIPPFeedbackBannerData.kt:144:50
Const 'val' initializer should be a constant value
✅ Build time report of 2m 57s has been received by Tracks.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':WooCommerce:compileWasabiDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner
 .GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

------------------------------------------------------------------------

Explanation: "Starting with AGP 8.0, the default values for these flags
have changed to improve build performance. AGP 8.0 generates R classes
with non-final fields by default."

For more info see: https://developer.android.com/build/releases/
gradle-plugin#default-changes