Build: Enable build config build feature for quicklogin and woocommerce
This is an AGP version '8.0' breaking change that changes the build
option default values, see build failure below:

------------------------------------------------------------------------

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':quicklogin'.
> com.android.builder.errors.EvalIssueException: defaultConfig contains
 custom BuildConfig fields, but the feature is disabled.

------------------------------------------------------------------------

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':WooCommerce'.
> com.android.builder.errors.EvalIssueException: Build Type 'debug'
 contains custom BuildConfig fields, but the feature is disabled.

------------------------------------------------------------------------

Explanation: "Starting with AGP 8.0, the default values for these flags
have changed to improve build performance. AGP 8.0 doesn't generate
'BuildConfig' by default. You need to specify this option using the DSL
in the projects where you need it."

For more info see: https://developer.android.com/build/releases/
gradle-plugin#default-changes