Build: Resolve all violating non final res references for android test
This is an AGP version '8.0' breaking change that changes the build
option default values, see build failure below:

PS: The alternative would be to disable the default, that is, having the
'android.nonFinalResIds' disabled, and not resolve all violating such
res references.

------------------------------------------------------------------------

> Task :WooCommerce:compileWasabiDebugAndroidTestKotlin FAILED
e: file:///Users/.../WooCommerce/src/androidTest/kotlin/com/woocommerce/
android/e2e/screens/TabNavComponent.kt:12:37
Const 'val' initializer should be a constant value
e: file:///Users/.../WooCommerce/src/androidTest/kotlin/com/woocommerce/
android/e2e/screens/TabNavComponent.kt:13:35
Const 'val' initializer should be a constant value
e: file:///Users/.../WooCommerce/src/androidTest/kotlin/com/woocommerce/
android/e2e/screens/TabNavComponent.kt:14:37
Const 'val' initializer should be a constant value
e: file:///Users/.../WooCommerce/src/androidTest/kotlin/com/woocommerce/
android/e2e/screens/TabNavComponent.kt:15:38
Const 'val' initializer should be a constant value
e: file:///Users/.../WooCommerce/src/androidTest/kotlin/com/woocommerce/
android/e2e/screens/login/EmailAddressScreen.kt:8:41
Const 'val' initializer should be a constant value
e: file:///Users/.../WooCommerce/src/androidTest/kotlin/com/woocommerce/
android/e2e/screens/login/EmailAddressScreen.kt:9:33
Const 'val' initializer should be a constant value
e: file:///Users/.../WooCommerce/src/androidTest/kotlin/com/woocommerce/
android/e2e/screens/login/MagicLinkScreen.kt:8:41
Const 'val' initializer should be a constant value
e: file:///Users/.../WooCommerce/src/androidTest/kotlin/com/woocommerce/
android/e2e/screens/login/PasswordScreen.kt:9:36
Const 'val' initializer should be a constant value
e: file:///Users/.../WooCommerce/src/androidTest/kotlin/com/woocommerce/
android/e2e/screens/login/PasswordScreen.kt:10:33
Const 'val' initializer should be a constant value
e: file:///Users/.../WooCommerce/src/androidTest/kotlin/com/woocommerce/
android/e2e/screens/login/SiteAddressScreen.kt:8:40
Const 'val' initializer should be a constant value
e: file:///Users/.../WooCommerce/src/androidTest/kotlin/com/woocommerce/
android/e2e/screens/login/SiteAddressScreen.kt:9:33
Const 'val' initializer should be a constant value
e: file:///Users/.../WooCommerce/src/androidTest/kotlin/com/woocommerce/
android/e2e/screens/login/WelcomeScreen.kt:10:34
Const 'val' initializer should be a constant value
e: file:///Users/.../WooCommerce/src/androidTest/kotlin/com/woocommerce/
android/e2e/screens/login/WelcomeScreen.kt:11:40
Const 'val' initializer should be a constant value
e: file:///Users/.../WooCommerce/src/androidTest/kotlin/com/woocommerce/
android/e2e/screens/moremenu/MoreMenuScreen.kt:16:36
Const 'val' initializer should be a constant value
e: file:///Users/.../WooCommerce/src/androidTest/kotlin/com/woocommerce/
android/e2e/screens/mystore/MyStoreScreen.kt:14:30
Const 'val' initializer should be a constant value
e: file:///Users/.../WooCommerce/src/androidTest/kotlin/com/woocommerce/
android/e2e/screens/mystore/StatsComponent.kt:8:37
Const 'val' initializer should be a constant value
e: file:///Users/.../WooCommerce/src/androidTest/kotlin/com/woocommerce/
android/e2e/screens/mystore/settings/BetaFeaturesScreen.kt:8:43
Const 'val' initializer should be a constant value
e: file:///Users/.../WooCommerce/src/androidTest/kotlin/com/woocommerce/
android/e2e/screens/mystore/settings/SettingsScreen.kt:14:33
Const 'val' initializer should be a constant value
e: file:///Users/.../WooCommerce/src/androidTest/kotlin/com/woocommerce/
android/e2e/screens/mystore/settings/SettingsScreen.kt:15:42
Const 'val' initializer should be a constant value
e: file:///Users/.../WooCommerce/src/androidTest/kotlin/com/woocommerce/
android/e2e/screens/mystore/settings/SettingsScreen.kt:16:36
Const 'val' initializer should be a constant value
e: file:///Users/.../WooCommerce/src/androidTest/kotlin/com/woocommerce/
android/e2e/screens/orders/CardReaderPaymentScreen.kt:8:36
Const 'val' initializer should be a constant value
e: file:///Users/.../WooCommerce/src/androidTest/kotlin/com/woocommerce/
android/e2e/screens/orders/CustomerDetailsScreen.kt:18:36
Const 'val' initializer should be a constant value
e: file:///Users/.../WooCommerce/src/androidTest/kotlin/com/woocommerce/
android/e2e/screens/orders/CustomerDetailsScreen.kt:19:38
Const 'val' initializer should be a constant value
e: file:///Users/.../WooCommerce/src/androidTest/kotlin/com/woocommerce/
android/e2e/screens/orders/CustomerDetailsScreen.kt:20:29
Const 'val' initializer should be a constant value
e: file:///Users/.../WooCommerce/src/androidTest/kotlin/com/woocommerce/
android/e2e/screens/orders/CustomerDetailsScreen.kt:21:34
Const 'val' initializer should be a constant value
e: file:///Users/.../WooCommerce/src/androidTest/kotlin/com/woocommerce/
android/e2e/screens/orders/OrderListScreen.kt:18:31
Const 'val' initializer should be a constant value
e: file:///Users/.../WooCommerce/src/androidTest/kotlin/com/woocommerce/
android/e2e/screens/orders/OrderListScreen.kt:19:31
Const 'val' initializer should be a constant value
e: file:///Users/.../WooCommerce/src/androidTest/kotlin/com/woocommerce/
android/e2e/screens/orders/OrderListScreen.kt:20:35
Const 'val' initializer should be a constant value
e: file:///Users/.../WooCommerce/src/androidTest/kotlin/com/woocommerce/
android/e2e/screens/orders/OrderListScreen.kt:21:41
Const 'val' initializer should be a constant value
e: file:///Users/.../WooCommerce/src/androidTest/kotlin/com/woocommerce/
android/e2e/screens/orders/PaymentSelectionScreen.kt:8:33
Const 'val' initializer should be a constant value
e: file:///Users/.../WooCommerce/src/androidTest/kotlin/com/woocommerce/
android/e2e/screens/orders/SingleOrderScreen.kt:19:43
Const 'val' initializer should be a constant value
e: file:///Users/.../WooCommerce/src/androidTest/kotlin/com/woocommerce/
android/e2e/screens/orders/SingleOrderScreen.kt:20:32
Const 'val' initializer should be a constant value
e: file:///Users/.../WooCommerce/src/androidTest/kotlin/com/woocommerce/
android/e2e/screens/orders/SingleOrderScreen.kt:21:37
Const 'val' initializer should be a constant value
e: file:///Users/.../WooCommerce/src/androidTest/kotlin/com/woocommerce/
android/e2e/screens/orders/SingleOrderScreen.kt:22:34
Const 'val' initializer should be a constant value
e: file:///Users/.../WooCommerce/src/androidTest/kotlin/com/woocommerce/
android/e2e/screens/orders/SingleOrderScreen.kt:23:34
Const 'val' initializer should be a constant value
e: file:///Users/.../WooCommerce/src/androidTest/kotlin/com/woocommerce/
android/e2e/screens/orders/SingleOrderScreen.kt:24:44
Const 'val' initializer should be a constant value
e: file:///Users/.../WooCommerce/src/androidTest/kotlin/com/woocommerce/
android/e2e/screens/orders/SingleOrderScreen.kt:25:35
Const 'val' initializer should be a constant value
e: file:///Users/.../WooCommerce/src/androidTest/kotlin/com/woocommerce/
android/e2e/screens/orders/SingleOrderScreen.kt:26:43
Const 'val' initializer should be a constant value
e: file:///Users/.../WooCommerce/src/androidTest/kotlin/com/woocommerce/
android/e2e/screens/orders/SingleOrderScreen.kt:27:38
Const 'val' initializer should be a constant value
e: file:///Users/.../WooCommerce/src/androidTest/kotlin/com/woocommerce/
android/e2e/screens/orders/SingleOrderScreen.kt:28:29
Const 'val' initializer should be a constant value
e: file:///Users/.../WooCommerce/src/androidTest/kotlin/com/woocommerce/
android/e2e/screens/orders/UnifiedOrderScreen.kt:23:35
Const 'val' initializer should be a constant value
e: file:///Users/.../WooCommerce/src/androidTest/kotlin/com/woocommerce/
android/e2e/screens/orders/UnifiedOrderScreen.kt:24:42
Const 'val' initializer should be a constant value
e: file:///Users/.../WooCommerce/src/androidTest/kotlin/com/woocommerce/
android/e2e/screens/orders/UnifiedOrderScreen.kt:25:38
Const 'val' initializer should be a constant value
e: file:///Users/.../WooCommerce/src/androidTest/kotlin/com/woocommerce/
android/e2e/screens/orders/UnifiedOrderScreen.kt:26:33
Const 'val' initializer should be a constant value
e: file:///Users/.../WooCommerce/src/androidTest/kotlin/com/woocommerce/
android/e2e/screens/orders/UnifiedOrderScreen.kt:27:40
Const 'val' initializer should be a constant value
e: file:///Users/.../WooCommerce/src/androidTest/kotlin/com/woocommerce/
android/e2e/screens/orders/UnifiedOrderScreen.kt:28:32
Const 'val' initializer should be a constant value
e: file:///Users/.../WooCommerce/src/androidTest/kotlin/com/woocommerce/
android/e2e/screens/orders/UnifiedOrderScreen.kt:29:35
Const 'val' initializer should be a constant value
e: file:///Users/.../WooCommerce/src/androidTest/kotlin/com/woocommerce/
android/e2e/screens/orders/UnifiedOrderScreen.kt:30:36
Const 'val' initializer should be a constant value
e: file:///Users/.../WooCommerce/src/androidTest/kotlin/com/woocommerce/
android/e2e/screens/orders/UnifiedOrderScreen.kt:31:37
Const 'val' initializer should be a constant value
e: file:///Users/.../WooCommerce/src/androidTest/kotlin/com/woocommerce/
android/e2e/screens/orders/UnifiedOrderScreen.kt:32:38
Const 'val' initializer should be a constant value
e: file:///Users/.../WooCommerce/src/androidTest/kotlin/com/woocommerce/
android/e2e/screens/orders/UnifiedOrderScreen.kt:33:37
Const 'val' initializer should be a constant value
e: file:///Users/.../WooCommerce/src/androidTest/kotlin/com/woocommerce/
android/e2e/screens/orders/UnifiedOrderScreen.kt:34:43
Const 'val' initializer should be a constant value
e: file:///Users/.../WooCommerce/src/androidTest/kotlin/com/woocommerce/
android/e2e/screens/orders/UnifiedOrderScreen.kt:35:29
Const 'val' initializer should be a constant value
e: file:///Users/.../WooCommerce/src/androidTest/kotlin/com/woocommerce/
android/e2e/screens/orders/UnifiedOrderScreen.kt:36:45
Const 'val' initializer should be a constant value
e: file:///Users/.../WooCommerce/src/androidTest/kotlin/com/woocommerce/
android/e2e/screens/products/ProductListScreen.kt:18:31
Const 'val' initializer should be a constant value
e: file:///Users/.../WooCommerce/src/androidTest/kotlin/com/woocommerce/
android/e2e/screens/products/SingleProductScreen.kt:15:46
Const 'val' initializer should be a constant value
e: file:///Users/.../WooCommerce/src/androidTest/kotlin/com/woocommerce/
android/e2e/screens/reviews/ReviewsListScreen.kt:15:31
Const 'val' initializer should be a constant value
e: file:///Users/.../WooCommerce/src/androidTest/kotlin/com/woocommerce/
android/e2e/screens/reviews/SingleReviewScreen.kt:14:40
Const 'val' initializer should be a constant value
e: file:///Users/.../WooCommerce/src/androidTest/kotlin/com/woocommerce/
android/e2e/screens/shared/FilterScreen.kt:15:29
Const 'val' initializer should be a constant value
✅ Build time report of 0m 46s has been received by Tracks.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task
 ':WooCommerce:compileWasabiDebugAndroidTestKotlin'.
> A failure occurred while executing
 org.jetbrains.kotlin.compilerRunner
 .GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

------------------------------------------------------------------------

Explanation: "Starting with AGP 8.0, the default values for these flags
have changed to improve build performance. AGP 8.0 generates R classes
with non-final fields by default."

For more info see: https://developer.android.com/build/releases/
gradle-plugin#default-changes